import './globals.css'
import type { Metadata } from 'next'
// eslint-disable-next-line camelcase
import { Roboto_Mono } from 'next/font/google'

const robotoMono = Roboto_Mono({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Kanban Pro',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={robotoMono.className}>
        <div className="bg-slate-100 flex flex-1 min-h-screen flex-col items-center justify-center">
          {children}
        </div>
      </body>
    </html>
  )
}
